# Generated by Django 6.0.7 on 2026-07-19 06:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baht_per_point', models.DecimalField(decimal_places=2, default=50.0, help_text='ทุกยอดซื้อกี่บาท ถึงจะได้ 1 คะแนน (เช่น 50 = ทุก 50 บาท ได้ 1 แต้ม)', max_digits=10)),
                ('point_expiry_days', models.PositiveIntegerField(default=365, help_text='จำนวนวันก่อนแต้มจะหมดอายุ นับจากวันที่ได้รับ')),
                ('expiry_warning_days', models.PositiveIntegerField(default=7, help_text='แจ้งเตือนล่วงหน้ากี่วันก่อนแต้มจะหมดอายุ')),
            ],
            options={
                'verbose_name': 'ตั้งค่าระบบสะสมแต้ม',
                'verbose_name_plural': 'ตั้งค่าระบบสะสมแต้ม',
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('earn', 'ได้รับแต้ม'), ('redeem', 'แลกแต้ม'), ('expire', 'แต้มหมดอายุ'), ('adjust', 'ปรับปรุงแต้ม (แอดมิน)')], max_length=10)),
                ('purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('points', models.IntegerField(help_text='ค่าบวก = ได้แต้ม, ค่าลบ = แลก/หมดอายุ/หัก')),
                ('balance_after', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('expire_date', models.DateField(blank=True, db_index=True, null=True)),
                ('remaining_points', models.IntegerField(blank=True, help_text='เฉพาะรายการ earn: แต้มจากก้อนนี้ที่ยังไม่ถูกใช้/หมดอายุ (สำหรับ FIFO redemption)', null=True)),
                ('expired_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customers.customer')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='customers.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'created_at'], name='loyalty_poi_custome_97013b_idx'), models.Index(fields=['tx_type', 'expire_date'], name='loyalty_poi_tx_type_0df513_idx')],
            },
        ),
    ]
