# Generated by Django 6.0.7 on 2026-07-12 05:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('EARN', 'รับคะแนน'), ('REDEEM', 'แลกคะแนน'), ('EXPIRE', 'คะแนนหมดอายุ'), ('ADJUST', 'ปรับปรุงคะแนน (แอดมิน)')], max_length=10)),
                ('points', models.IntegerField(help_text='ค่าบวก = ได้รับ, ค่าลบ = แลก/หมดอายุ/หัก')),
                ('purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customers.customer')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.staffprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_points', models.PositiveIntegerField()),
                ('remaining_points', models.PositiveIntegerField()),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_batches', to='customers.customer')),
                ('origin_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='points.pointtransaction')),
            ],
            options={
                'ordering': ['expires_at'],
                'indexes': [models.Index(fields=['customer', 'is_expired', 'expires_at'], name='points_poin_custome_3a795c_idx')],
            },
        ),
    ]
